---
issuer: http://www.ood.com:5556
storage:
  type: sqlite3
  config:
    file: "/etc/ood/dex/dex.db"
web:
  http: 0.0.0.0:5556
telemetry:
  http: 0.0.0.0:5558
connectors:
- type: ldap
  name: LDAP
  id: ood
  config:
    #Your active directory, with TLS enabled
    host: www.ood.com:389
    insecureNoSSL: true
    insecureSkipVerify: false
    startTLS: false
    #The AD user the connector should authenticate as. Modify domain name (dc) as appropriate.
    bindDN: cn=Manager,dc=localhost
    #The AD user's password
    bindPW: manager
    usernamePrompt: Corporate Email Address
    userSearch:
      baseDN: cn=Manager,dc=localhost
      filter: "(objectClass=posixAccount)"
      username: uid
      idAttr: DN
      emailAttr: mail
      nameAttr: cn
    groupSearch:
      # Modify domain name as appropriate.
      baseDN: cn=Group,dc=localhost
      filter: "(objectClass=posixGroup)"
      userMatchers:
      - userAttr: DN
        groupAttr: member
      nameAttr: cn
staticClients:
  - id: www.ood.com   
    redirectURIs:
    - http://www.ood.com/oidc
    name: OnDemand
    secret: 5d6487b6-acf0-4af0-ba87-26ae98cb6285
oauth2:
  skipApprovalScreen: true
enablePasswordDB: true   
staticPasswords:
- email: ood@localhost
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: ood
  userID: '08a8684b-db88-4b73-90a9-3cd1661f5466'
frontend:
 dir: "/usr/share/ondemand-dex/web"
 theme: ondemand

